### ISSUE TITLE
Technical Meeting in Munich

### ISSUE THREAD

**Issue by kstrohmayer** [semify-eda/tristan#4]
Meeting in Munich: 14-15. Nov
  - [x] Check if required --> won't attend, only add the presentation
   
Required for the meeting:
  - [x] Single page presentation

**Comment by adam-hrvth** [comment]
I've started working on the [presentation](https://nxp1.sharepoint.com/:p:/r/sites/KDT-RISCV/_layouts/15/Doc.aspx?sourcedoc=%7B49488606-F0C8-4A8D-BA30-BFDF08D34F96%7D&file=TRISTAN_WP2%20technical%20Meeting_MUC_20231114.pptx&action=edit&mobileredirect=true), and our work item is on slide 43. I will cross-reference the WP6 report once it's added to SharePoint.
