### ISSUE TITLE
Cumaltive report

### ISSUE THREAD

**Issue by kstrohmayer** [semify-eda/tristan#5]
Report done, needs to be added to the SharPoint

**Comment by adam-hrvth** [comment]
The cumulative report for WP6 has been added to the [SharePoint](https://nxp1.sharepoint.com/:w:/r/sites/KDT-RISCV/_layouts/15/Doc.aspx?sourcedoc=%7B95A7595D-270B-4378-B0AD-479B82980970%7D&file=TRISTAN-IMR-Cumulative-Report_WP6_M07%20-%20M12.docx&action=default&mobileredirect=true).
