### ISSUE TITLE
Design specification for demonstrator

### ISSUE THREAD

**Issue by kstrohmayer** [semify-eda/tristan#6]
More comprehensive report.

Add link to document on sharepoint

**Comment by kstrohmayer** [comment]
Indicate how to visualize the improvement of the custom instruction

**Comment by adam-hrvth** [comment]
The "in-progress" report has been added to our [Google Drive.](https://docs.google.com/document/d/1gjGRFRDhdS6iK5SrPrLqyLMYURPyIJbS/edit)

**Comment by adam-hrvth** [comment]
Hi @kstrohmayer and @mole99, I have finished the [report](https://docs.google.com/document/d/1gjGRFRDhdS6iK5SrPrLqyLMYURPyIJbS/edit?usp=sharing&ouid=116851939288601517356&rtpof=true&sd=true) for the demonstrator. Please review it and provide some feedback. If no changes are required, I will upload it to SharePoint.

**Comment by kstrohmayer** [comment]
Thanks for the report. Looks fine in general. 

Some questions for my side:
- Are we able to provide already some numbers for the achievable compression ratio
- Are we able to provide already some numbers for the achievable performance speed-up

**Comment by adam-hrvth** [comment]
> Thanks for the report. Looks fine in general.
> 
> Some questions for my side:
> 
>     * Are we able to provide already some numbers for the achievable compression ratio
> 
>     * Are we able to provide already some numbers for the achievable performance speed-up

@mole99, you've been making progress on running the encoding on hardware. Do you have any numerical data we could include in the report?

**Comment by mole99** [comment]
We can measure the time it takes for a full encoding + decoding with a soft cntb and then a second time using the current hard cntb. The ratio will give us the speedup.
We can do this together on Thursday morning.
For the compression ratio I think there are some numbers in Marios thesis.

**Comment by adam-hrvth** [comment]
Sure, next Thursday is good for me. But just to let you know, I've got to submit the report by the end of Tuesday, so I'll have to skip the performance speed-up part. I'll check Mario's thesis for the compression ratio.

**Comment by adam-hrvth** [comment]
I've added the report to [SharePoint](https://nxp1.sharepoint.com/:w:/r/sites/KDT-RISCV/Shared%20Documents/1.%20Project%20Implementation%20(consortium)/05.%20Deliverables/YR1/WP6/TRISTAN%20-%20Design%20Specifications%20of%20demonstrator%20SMART_WAVE.docx?d=w371719b340b7411f812ee60d0f5b7c7c&csf=1&web=1&e=dbAocl).  I've included Mario's results on the compression/decompression improvements.
Currently, it doesn't include the results on the achievable performance speed-up, but we can add that during the actual demonstration.
